### PR TITLE
replace `...entity` to `...entry` 

### PR DESCRIPTION
**Pull request by Tom-Shorter**
PR in response to #63 

SchemasPerEntity -> SchemasPerEntryType
entity -> entry

Ignored all occurrences of entity within the License, these were left as is. 

May need to modify the readme, line 35
Entity names: `PascalCase` -> Entry names: `PascalCase`

### CODE REVIEW

**Review by mbaudis — APPROVED** [review]

**Comment by jrambla** [comment]
Well spotted.
Two comments on my side:
1- We must warn the implementers before doing that change as it will break every implementation.
2- The files with "NCIT:C20181" should not change "Conceptual Entity" as it is the actual label for that ontology term.

**Comment by Tom-Shorter** [comment]
@jrambla I've changed occurrences of Conceptual entry back to Conceptual Entity (ignore what the commit message says!)

**Comment by mbaudis** [comment]
@Tom-Shorter @jrambla I'm fine w/ it. Won't break our implementation anyway (I think...).

**Comment by mbaudis** [comment]
@jrambla @Tom-Shorter This is still open - what to do with it now? Should have been merged, IMO ... Now: Should we first tag the current Beacon v2 version as 2.0.0 and then merge this in as patch? @mrueda ?

**Comment by Tom-Shorter** [comment]
There might be additional mentions of entity now and the spec has changed since this was created so it might be best to close this PR and update the unified repo instead

**Comment by mbaudis** [comment]
@Tom-Shorter Agree. I'll open an issue there - feel free to take it from there ...

**Pull request closed without merging**
